[[hooks]]
stage = "pre_build"
command = "./tailwindcss.exe"
command_arguments = ["-i", "./style/input.css", "-o", "./style/output.css"]

[build]
target = "./index.html"

[watch]
ignore = ["./src-tauri"]

[serve]
address = "127.0.0.1"
port = 1420
open = false
